### ISSUE TITLE
Crash with VS 2019 version 16.1.0

### ISSUE THREAD

**Issue by galatilu** [simonp22/AnkhSVN#4] opened 2019-05-23 08:40 UTC
If I try to open "Pending changes" window or try to commit some changes I have a crash from AnkhSVn.
This is the crash: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ankh.VS.Selection.CommandState.LoadThemeData()
   at Ankh.VS.Selection.CommandState.get_ThemeDefined()
   at Ankh.UI.PendingChanges.Commits.PendingCommitItem.RefreshText(IAnkhServiceProvider context)
   at Ankh.UI.PendingChanges.Commits.PendingCommitItem..ctor(PendingCommitsView view, PendingChange change)
   at Ankh.UI.SccManagement.ProjectCommitDialog.Reload()
   at Ankh.UI.SccManagement.ProjectCommitDialog.LoadChanges(IEnumerable`1 changeWalker)
   at Ankh.UI.SccManagement.ProjectCommitDialog.LoadItems(IEnumerable`1 iEnumerable)
   at Ankh.Commands.ItemCommitCommand.OnExecute(CommandEventArgs e)
   at Ankh.Commands.CommandMapItem.OnExecute(CommandEventArgs e)
   at Ankh.Commands.CommandMapper.Execute(AnkhCommand command, CommandEventArgs e)

With the previous version of VS AnkhSvn worked well, the problems began with this last version.

**Comment by simonp22** [comment] 2019-05-23 09:04
Please see 
Duplicate of #3

**Closed as completed by simonp22** 2019-05-23 09:04 UTC

**Comment by galatilu** [comment] 2019-05-23 09:17
Sorry, I didn't see it, I solved the problem with #3.
