### ISSUE TITLE
Pending changes windows display incorrectly

### ISSUE THREAD

**Issue by LouisCheung85** [simonp22/AnkhSVN#8] opened 2019-05-28 06:19 UTC
When I upgrade to Visual studio 2019 version 16.1.1,the pending changes window only show the toolbar,the detail part can't display.

**Comment by simonp22** [comment] 2019-05-28 08:15
Duplicate of #3 Related to the deprecated APIs that I am working to remove

**Closed as completed by simonp22** 2019-05-28 08:15 UTC
