### ISSUE TITLE
Exception when trying to show the Changes tool window

### ISSUE THREAD

**Issue by Tdue21** [simonp22/AnkhSVN#6] opened 2019-05-24 06:27 UTC
When I try to open the "View Changes" tool window, I get this exception: 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ankh.VS.Selection.CommandState.LoadThemeData()
   at Ankh.VS.Selection.CommandState.get_ThemeDefined()
   at Ankh.UI.PendingChanges.Commits.PendingCommitItem.RefreshText(IAnkhServiceProvider context)
   at Ankh.UI.PendingChanges.Commits.PendingCommitItem..ctor(PendingCommitsView view, PendingChange change)
   at Ankh.UI.PendingChanges.Commits.PendingCommitItemCollection.GetWrapItem(PendingChange inner)
   at Ankh.Collections.KeyedWrapNotifyCollection`3.WrapInnerKeyedCollection.ResetCollection()
   at Ankh.Collections.KeyedWrapNotifyCollection`3..ctor(IKeyedNotifyCollection`2 collection, Object context)
   at Ankh.UI.PendingChanges.Commits.PendingCommitsView.Ankh.UI.IPendingChangeUI.set_Items(IKeyedNotifyCollection`2 value)
   at Ankh.UI.PendingChanges.PendingCommitsPage.HookList()
   at Ankh.UI.PendingChanges.PendingCommitsPage.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at Ankh.UI.PendingChanges.PendingChangesToolControl.ShowPanel(PendingChangesPage page, Boolean select)
   at Ankh.UI.PendingChanges.PendingChangesToolControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at Ankh.VSPackage.AnkhToolWindowPane.get_Window()
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsUIElementPane.CreateUIElementPane(Object& uiElement)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.Init(Boolean initSize)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(String pszName, Int32 fDockViewOn, Int32 fDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, UInt32 dwToolWinId, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Int32& pfDefaultPosition, Guid& rguidCmdUI, IVsWindowFrame& ppWindowFrame)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Package.CreateFrameForToolWindow(ToolWindowCreationResult result, Int32 id, Guid persistenceGuid)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags, Object context, Guid persistenceGuid)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, Object context)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id)
   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
   at Ankh.VSPackage.AnkhSvnPackage.ShowToolWindow(AnkhToolWindow toolWindow, Int32 id, Boolean create)
   at Ankh.VSPackage.AnkhSvnPackage.ShowToolWindow(AnkhToolWindow window)
   at Ankh.Commands.UI.ShowToolWindows.OnExecute(CommandEventArgs e)
   at Ankh.Commands.CommandMapItem.OnExecute(CommandEventArgs e)
   at Ankh.Commands.CommandMapper.Execute(AnkhCommand command, CommandEventArgs e)
```

**Comment by simonp22** [comment] 2019-05-24 08:13
Duplicate of #3

**Closed as completed by simonp22** 2019-05-24 08:13 UTC
